on:
   push:
     branches:
       - main
       - 'releases/*'
     paths:
       - "src/**"
   pull_request:
    branches:
      - main
      - 'releases/*'
    paths:
      - "src/**"

jobs:
   test:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout code
         uses: actions/checkout@v5

       - name: Run tests
         run: npm test              
